from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from zcpv.dfl import crunch_match, learn_zone_values
from zcpv.statsbomb import collapse_xt_grid


REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_ROOT = REPO_ROOT / "models" / "data"
FRONTEND_ROOT = REPO_ROOT / "frontend"


def main():
    parser=argparse.ArgumentParser(description='Compute ZCPV from the official DFL/IDSSE release.')
    parser.add_argument('--data-root',type=Path,default=DATA_ROOT/'raw/dfl')
    parser.add_argument('--match',default='J03WMX')
    parser.add_argument('--output',type=Path,default=FRONTEND_ROOT/'app/match-data.generated.ts')
    parser.add_argument('--xt-grid',type=Path,default=DATA_ROOT/'processed/models/xt_grid.npy',help='Trained fine-grid xT model; falls back to the seven-match DFL fit when absent')
    parser.add_argument('--all',action='store_true',help='Process every complete match and write a combined dataset')
    args=parser.parse_args()
    event_paths=sorted(args.data_root.glob('*/events.xml'))
    if not event_paths: raise SystemExit('No DFL event files found')
    if args.xt_grid.exists():
        zone_values=collapse_xt_grid(np.load(args.xt_grid))
        zone_model='StatsBomb World Cup 2022 xT (16x12 collapsed to 4x3)'
    else:
        zone_values=learn_zone_values(event_paths)
        zone_model='DFL seven-match observed-event xT fallback'
    if args.all:
        results=[]
        for match_dir in sorted(args.data_root.iterdir()):
            if all((match_dir/name).exists() for name in ('match.xml','events.xml','positions.xml')):
                print(f"Crunching {match_dir.name}...",flush=True)
                results.append(crunch_match(match_dir,event_paths,zone_values))
        result={'provenance':{'source':'DFL / IDSSE','license':'CC BY 4.0','doi':'10.1038/s41597-025-04505-y','action_model':zone_model},'matches':results}
    else:
        result=crunch_match(args.data_root/args.match,event_paths,zone_values)
        result['provenance']['action_model']=zone_model
    args.output.parent.mkdir(parents=True,exist_ok=True)
    serialized=json.dumps(result,ensure_ascii=False,indent=2)
    if args.output.suffix == '.ts':
        serialized=f'// Generated by models/scripts/crunch_dfl.py. Do not edit by hand.\nconst matchData = {serialized};\nexport default matchData;\n'
    args.output.write_text(serialized,encoding='utf-8')
    count=sum(len(m['players']) for m in result['matches']) if args.all else len(result['players'])
    print(f"Wrote {args.output} with {count} player rows")

if __name__=='__main__': main()
