// Generated by scripts/train_baselines.py.
const modelReport = {
  "dataset": {
    "name": "FIFA World Cup 2022",
    "provider": "StatsBomb Open Data",
    "repository": "https://github.com/hudl/open-data",
    "matches": 64,
    "train_matches": 51,
    "test_matches": 13,
    "train_actions": 116193,
    "test_actions": 32929,
    "test_start": "2022-12-04",
    "split": "chronological by match date"
  },
  "vaep": {
    "state": "current action plus two previous actions",
    "horizon": "goal scored or conceded within 10 actions",
    "estimator": "histogram gradient boosting",
    "score": {
      "events": 32929,
      "positive_rate": 0.01342,
      "brier": 0.01201,
      "baseline_brier": 0.01326,
      "brier_improvement_pct": 9.45,
      "log_loss": 0.06047,
      "roc_auc": 0.7864,
      "calibration_error": 0.0037
    },
    "concede": {
      "events": 32929,
      "positive_rate": 0.00437,
      "brier": 0.00434,
      "baseline_brier": 0.00436,
      "brier_improvement_pct": 0.59,
      "log_loss": 0.02634,
      "roc_auc": 0.8534,
      "calibration_error": 0.00312
    }
  },
  "xt": {
    "grid": [
      16,
      12
    ],
    "nonzero_zones": 192,
    "max_zone_value": 0.33679,
    "test_actions_valued": 21954,
    "mean_absolute_action_value": 0.00472
  },
  "notes": [
    "StatsBomb events train the event baselines; DFL tracking remains a separate evaluation source.",
    "The held-out matches are never used to fit either probability model or the xT grid.",
    "These are baseline validation metrics, not evidence that ZCPV is already superior."
  ]
};
export default modelReport;
