// Generated by scripts/train_zcpv.py.
const researchV1 = {
  "schema_version": "1.0.0",
  "model_version": "pivot-v1-research",
  "generated_at": "2026-09-26T00:10:37.346286+00:00",
  "config_hash": "3f838e797241f107",
  "profile_cutoff": null,
  "status": "insufficient_data",
  "reason": "J03WMX: 20 non-penalty shots lack xG",
  "units": "non-penalty expected goals impact per 90",
  "reference": "exposure-weighted average player in the training competition",
  "players": null,
  "data_summary": {
    "dfl_matches": 7,
    "tracking_source": "DFL/IDSSE",
    "pipeline_stages": {
      "features": "complete",
      "state": "insufficient_data",
      "profiles": "insufficient_data",
      "impact": "insufficient_data",
      "evaluate": "insufficient_data"
    }
  },
  "limitations": [
    "v1 estimates association under regularized lineup and context controls, not causal player value",
    "goalkeepers are retained as lineup controls but excluded from public outfield rankings",
    "upstream situation-model uncertainty is not included unless explicitly reported"
  ]
} as const;
export default researchV1;
