// Generated by scripts/train_zcpv.py.
const researchV1 = {
  "schema_version": "1.0.0",
  "model_version": "zcpv-v1-research",
  "generated_at": "2026-09-25T15:37:16.987077+00:00",
  "config_hash": "2db3b89c0a931ec4",
  "profile_cutoff": null,
  "status": "insufficient_data",
  "reason": "The seven DFL matches lack provider xG and are too small for credible chronological player-impact estimation. Infrastructure and audits are runnable; no v1 player ratings are published.",
  "units": "non-penalty expected goals impact per 90",
  "reference": "exposure-weighted average player in the training competition",
  "players": null,
  "data_summary": {
    "dfl_matches": 7,
    "tracking_source": "DFL/IDSSE",
    "xg_target": "unavailable"
  },
  "limitations": [
    "v1 estimates association under regularized lineup and context controls, not causal player value",
    "goalkeepers are retained as lineup controls but excluded from public outfield rankings",
    "upstream situation-model uncertainty is not included unless explicitly reported"
  ]
} as const;
export default researchV1;
